### ISSUE TITLE
When I get a notification to join a quest, the notification is in the wrong language

### ISSUE THREAD

**Issue by solkaz** [HabitRPG/habitica-android#898] opened 2017-11-21 15:40 UTC
When I recieve a notification, I get a message in Portuguese, when my application's language is English. Furthermore, I'm not able to accept or decline the invitation.

**Comment by Alys** [comment] 2017-11-21 21:08
Thanks for your report but we have this recorded at https://github.com/HabitRPG/habitica/issues/8718 so I'll close this issue. It won't be related to the inability to accept or reject the invitation; that's most likely caused by the quest owner or party leader already having force-started the quest.

When you find bugs, the best place to report them is the Report a Bug guild, which you can reach from the Help menu on the website or the Guilds menu item on the mobile app (you'll find it in the "Public Guilds" section). We can see your account there so we can give specific advice about any problem you might be having. If my guess about the invitation isn't correct, post there and briefly describe what happens when you try to accept or reject the invitation.

**Closed by Alys** 2017-11-21 21:08 UTC
