### ISSUE TITLE
Empty Lists when App was in Background for longer time

### ISSUE THREAD

**Issue by PatriciaHeimfarth** [HabitRPG/habitica-android#1572] opened 2021-06-21 21:28 UTC
**Describe the bug**
When I have opened the app and leave it in the background for some time all lists are empty when I open it again. Only a restart helps with that.

**To Reproduce**
- Open the app on Android
- Leave it in background for an hour or so
- Open it again

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZ1
 - OS: Android 9
 - App Version: Newest

**Comment by shanaqui** [comment] 2021-06-25 12:08
Hi Patricia! Thanks for the report! This is a duplicate of #1504, which is already due to be fixed in version 3.3, so I'm closing this one. 

In future, if you do make issues here, can you please include the version of the app you're on even if you think it's the newest? There are sometimes multiple versions at once due to the beta versions and staged rollouts of the app. :) You can find the number under Menu>About within the app. You can also just report things via Menu>About>Report a Bug, which will automatically generate an email with all the info about your system that we need. Then you can write there what happened, and someone will be able to create a bug or add info to the right issue for you! :)

**Closed by shanaqui** 2021-06-25 12:08 UTC
Labels: Type: Bug
