### ISSUE TITLE
Turkey mount and Veteran Wolf pet missing in app, present on website.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica-android#694] opened 2017-01-14 20:27 UTC
**In the app** (note the scroll bar shows that there's nothing else below):

![image](https://cloud.githubusercontent.com/assets/5641207/21957824/a7e96fec-da54-11e6-80b7-168d796e4cac.png)

**On the website**:

![image](https://cloud.githubusercontent.com/assets/5641207/21957834/ba2f2200-da54-11e6-8ced-c0f1f8ce2ace.png)

For verification, my UUID is f9c89bba-abf8-4f20-a974-cf1550ff603f

**Comment by Alys** [comment] 2017-01-15 04:41
Confirmed. The Turkey-Base mount and Turkey-Gilded mounts do not appear on the Android app.

Thanks @khipkin!

**Comment by kent12t** [comment] 2018-01-18 11:17
@Alys should this one be merged with issue [#809](https://github.com/HabitRPG/habitica-android/issues/809)? both are on the rare pets section, not showing on Android while visible on website, just two different animals :)

**Comment by Alys** [comment] 2018-01-18 11:36
@kent12t Good point! They might as well go together. I've updated the title of this issue.

**As originally reported in https://github.com/HabitRPG/habitica-android/issues/809, the Veteran Wolf Pet does not appear in Stable's "Rare Pets" section.**

**Comment by Alys** [comment] 2018-04-16 21:58
I'm reopening this because there's still problems with the Veteran Wolf pet and the the Turkey mounts appearing in the "Rare" section of the Stable.

Normally, I have the Cerebus Wolf (the Kickstarter reward) and the Veteran Wolf pets, and both of those appear in the Rare section, however the count shows 1 instead of 2. (Cerebus is invisible but that will be an unrelated problem, likely because it's animated, and is minor since it affects few users, all of whom will be website users.) These two screenshots show that I have both pets but that the count for Wolf is 1:

![screenshot_2018-04-17-04-58-31](https://user-images.githubusercontent.com/1495809/38837117-1f651f80-4214-11e8-99b2-c6c36bad607d.png)
![screenshot_2018-04-17-04-58-19](https://user-images.githubusercontent.com/1495809/38837116-1f26d0fe-4214-11e8-812a-7f82296cce44.png)

If I delete the Cerebus pet from my account, then I no longer see the Wolf box under the Rare section - i.e., the Veteran Wolf does not appear for me.

Similarly, I have two Turkey mounts (Base and Gilded). They both appear in the app but with a count of 1 instead of 2:
![screenshot_2018-04-17-07-49-37](https://user-images.githubusercontent.com/1495809/38837121-2082c21e-4214-11e8-97ff-f9f27ce702ac.png)
![screenshot_2018-04-17-07-49-19](https://user-images.githubusercontent.com/1495809/38837120-2020819e-4214-11e8-94a5-8036f7b95a2d.png)


If I delete one Turkey mount from my account, I no longer see either of them in the app.

It's as if the count of these rare pets and mounts is off by one and that causes the subsections for those beasts to be hidden when there's only 1.

Also, can the "Rare" label under both Pets and Mounts be changed to "Special" for consistency with the website and iOS app?

**Closed** 2019-05-01 20:44 UTC
Labels: Help wanted, Priority: minor, Type: Bug
