### ISSUE TITLE
Crystal armor isn't visible on avatar or in equipment list

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica-android#485] opened 2016-03-26 03:49 UTC
Here it is, listed among my equipped stuff:
![image](https://cloud.githubusercontent.com/assets/5641207/14057886/d05dda48-f2e3-11e5-8b20-2e5790cc25a7.png)

And yes, I also have the crystal armor equipped as part of my costume.

Yet it doesn't show up on my avatar!  You can just see the shirt I have on as my base layer.

![image](https://cloud.githubusercontent.com/assets/5641207/14057884/c7d34d2c-f2e3-11e5-968a-bb20fedcb1c6.png)

**Comment by Alys** [comment] 2016-10-06 21:05
I'm reopening this because the same armor isn't appearing on the avatar for citrusella, the ghost wench ( 2d6ef231-50b4-4a22-90e7-45eb97147a2c ). She can't see it when she views her avatar in the app, and I can't see it when I view her profile in the app. It is visible on the website.

**Comment by citrusella** [comment] 2016-10-07 00:59
I *can* see its image in the list of armor (on profile and in the equipment settings), though, in case that's important. Just not on the avatar itself.

**Comment by citrusella** [comment] 2017-11-17 09:05
...Is there a reason this was closed? I still don't see the armor on my avatar in version 1.3 (1957). 0_o

**Comment by Alys** [comment] 2017-11-17 10:58
Confirmed that the Crystal Armor doesn't appear on my avatar in version 1.3 (1957). It is possible that a fix has been made but hasn't been sent to Google Play yet but there's no commit or PR linked to this issue so I'm guessing this was closed by accident and I'm reopening it.

**Comment by saraolson** [comment] 2017-11-17 20:24
I closed cause I could see crystal armor on my avatar so figured it was fixed since this is pretty old, so if its still not workin nevermindddddd lol

**Comment by citrusella** [comment] 2017-11-17 20:48
Can you see the armor or just the hat? When I put on the outfit to see if this was fixed (I was weirdly skeptical yet excited), I put on both because I forgot the headwear worked just fine. XP

**Comment by kent12t** [comment] 2017-12-06 04:43
I have the same problem here! Logging this in so the issue won't be closed;) (UUID: b82b7aa8-161f-4b02-aef9-4a319e47f7b2)

**Closed** 2018-02-12 15:11 UTC
Labels: Help wanted, Priority: medium, Type: Bug
