### ISSUE TITLE
dailies mislabeled on launch but resets when refreshed

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1843] opened 2022-08-26 14:45 UTC
> Device: Google Pixel 5a 5G
> Android Version: 32
> AppVersion: Version 4.0 (4320)
> User ID: 8f0f2f48-73b0-4b27-a95a-40603cc919e7
> Level: 51
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 5
> Timezone Offset: 420
> Details:
> Weird little display bug. I have quite a few Dailies - and for the last couple weeks or so, when I open the app and shift to that view, one or two are mislabeled. That is, a daily near the top of the list is labeled with the name of one lower down. In the screenshots I'm sending, Daily in the second shot is mislabeled Eat Meal in the first - the only difference between the two is that I pulled down to refresh between the two shots. So it's not hard to fix... But it's disconcerting and confusing and happening every (or almost every) morning.
> 
> It's different at times - sometimes more than one is mislabeled, and different ones, and different mislabels. But mostly Daily is called something from further down the list, usually but not always Eat meal.

**Comment by AdamWier** [comment] 2022-09-29 15:38
Hello, I'm not sure if this is systematic, but I have at least reproduced it as a user with my own phone. I would be interested in helping out. I see the issue is marked as needs investigation. Is that because you're still trying to find an exact scenario? Is there some way I could help?

**Comment by saraolson** [comment] 2022-10-03 16:17
@AdamWier hi there! yes indeed, the needs investigation is there because we haven't been able to reproduce and find the cause yet. if you're able to reliably reproduce the issue and can provide the steps or any extra details that would be helpful.

**Comment by AdamWier** [comment] 2022-10-03 16:36
Okay, I'll see what I can find!

**Comment by zakmetmoes** [comment] 2023-01-10 07:13
I'm gonna give this issue a try. I am a novice android programmer but this bugs seems simple. i can already reproduce this issue by closing the app and opening it again.

**Comment by saraolson** [comment] 2023-01-26 14:31
we made some improvements in 4.1 that may have fixed this issue. if anyone still experiences it after updating, we'll reopen!

**Closed by saraolson** 2023-01-26 14:31 UTC
Labels: Type: Bug, Help wanted, Status: issue: needs investigation
