### ISSUE TITLE
BottomBar partially behind Navigation Bar

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1172] opened 2019-06-05 11:49 UTC
In the last beta update of the application, the action buttons were somewhat hidden, making it impossible to handle them properly. [See screenshot](https://snag.gy/vYODRL.jpg).

P.s.: The model of my smartphone is the Xiaomi A2 Lite.

(Translated with Google Translate)

**Comment by phillipthelen** [comment] 2019-06-05 14:19
Are you using something to change the appearance of your navigationbar? (the bar at the bottom with the back, home and app switcher buttons).
Which android version are you using?

**Comment by matheusvictor** [comment] 2019-06-05 14:41
@phillipthelen: No. I just updated the app to the latest BETA version.
I'm using Android One 9

**Comment by saraolson** [comment] 2019-06-05 16:41
got another report of this with this device info:
Device: OnePlus6
Android Version: 28
AppVersion: Version 1.10 (2145) BETA

**Comment by saraolson** [comment] 2019-06-05 16:43
im adding this to 1.10 because its rather disruptive and we already have a few reports in just beta

**Comment by phillipthelen** [comment] 2019-06-06 16:18
We just pushed a redesigned bottom navigation bar to the beta channel, that should fix this issue. It is still not 100% finished and being tweaked, but is usable.

![Screenshot_1559833726](https://user-images.githubusercontent.com/298062/59048972-47ea2300-8887-11e9-9b19-7fe81189240c.png)
![Screenshot_1559833733](https://user-images.githubusercontent.com/298062/59048973-4882b980-8887-11e9-934d-9cefba944429.png)

**Comment by phillipthelen** [comment] 2019-06-10 14:03
Also saw this happen on a Huawei Mate 20 with android 9.

**Comment by matheusvictor** [comment] 2019-06-10 18:58
@phillipthelen, cool! I did update the app on my device, but the problem continues. See this screenshot:
![app mobile](https://user-images.githubusercontent.com/12521391/59219298-85f18a80-8b98-11e9-96c2-9ac46d3d3144.jpeg)

**Comment by saraolson** [comment] 2019-06-10 20:15
this might be caused by devices that have the ability to hide their navigation bars in the settings. because they have the ability, even if the setting isn't turned on, it could be conflicting with some way we render the bottom bar. so far, it seems all devices that have reported this problem have that setting. will be investigating soon.

**Comment by matheusvictor** [comment] 2019-06-10 21:49
@saraolson, I though it but I have tested too. The problema continues. Soon I show a screenshot

**Comment by phillipthelen** [comment] 2019-06-11 07:54
Since the navbar looks completely different, what exactly did you change?

**Comment by matheusvictor** [comment] 2019-06-11 11:34
@phillipthelen, I changed the bottons for a single one. This option is available on my device ,but I don't have sure about the others

**Closed** 2019-06-13 15:12 UTC
Labels: Priority: medium, Type: Bug
