### ISSUE TITLE
The developers crystal armour is not displayed correctly

### ISSUE THREAD

**Issue by AlbRoehm** [HabitRPG/habitica-android#698] opened 2017-01-19 13:12 UTC
When the crystal armor(contributor rewards) is equipped, the character is displayed not wearing an armor at all.

**Comment by Atomk** [comment] 2017-01-19 13:41
Did you find this bug by yourself or it was reported by someone? Because I reported this a few months ago via the in-app feedback feature but maybe it is better to just create an issue here on Github.

**Comment by AlbRoehm** [comment] 2017-01-19 13:44
Just got the armor a few days ago and found it out by playing around with it.

**Comment by mandyzhou** [comment] 2017-01-20 16:26
This is a duplicate of #485.

**Closed** 2017-01-20 17:17 UTC
