### ISSUE TITLE
Devices with Notches cause content to be drawn behind notch and/or navigation bar.

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1071] opened 2018-11-12 16:37 UTC
Not sure if this is fixed yet, but if it is, an easy issue to close! Based on this email, it sounds like this pixel problem is a pretty serious display issue if people are struggling to just use the app. This might effect the task nav? Including report:

"Love your work but sadly after update my phone I'm really struggling with the app. The GUI is designed in a way where anyone using the latest pixel and maybe all users on the latest Android system can't click on any of the bottom options because the home key overlaps them."

**Comment by phillipthelen** [comment] 2018-11-16 16:19
I finally managed to reproduce the issue in the android emulator. It is caused by the Pixel 3 XL having a notch. In the developer options on a device, there is an option to simulate a device with a cutout. When one of the options for that is activated, the app doesn't inset the content correctly anymore.

**Comment by chikka** [comment] 2018-11-20 13:45
@saraolson can i take it up?

**Comment by phillipthelen** [comment] 2018-11-26 17:58
@chikka This was already fixed last week. Sorry, I forgot to close the issue. The update containing the fix is now also released on the play store (1.6.1)

**Closed by phillipthelen** 2018-11-26 17:58 UTC
Labels: Help wanted, Priority: important, Type: Bug
