### ISSUE TITLE
App crashes when trying to load Menu>Guilds

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1532] opened 2021-04-12 13:10 UTC
> Device: Sony F5321
> Android Version: 25
> AppVersion: Версия 3.2.3 (2913)
> BETA
> User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
> Level: 87
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 16
> Timezone Offset: -120
> Details:
> 
> Hello,
> 
> My app crashes when I try to open guilds via Menu > Guilds. It doesn't open the guild list but just shuts down. I can access guilds by clicking on notifications though.
> I've tried clearing cache and checked for updates. Did not try to uninstalling and reinstalling the app.
> IIRC this kind of behavior happened before, so maybe it can be fixed the same way.
> 
> Thank you and have a great day!
> 
> Nana 

Uninstall/reinstall didn't help either.

**Comment by saraolson** [comment] 2021-04-12 13:38
i cant reproduce so maybe somethin with their guild list?

**Comment by Nakonana** [comment] 2021-04-12 16:29
@saraolson how would I test it if it was my guild list...? I tried logging into a different account that has a different list of guilds but got the same result.

**Comment by saraolson** [comment] 2021-04-12 17:54
@Nakonana well that is certainly one way, but also android keeps a cache so i would say try to log out of habitica, go to settings > storage > apps > habitica > clear all your cache and data. log into the different account and see if guild list loads?

if it does, then you might be able to try the same steps and load the original account and see if it crashes again?

**Comment by saraolson** [comment] 2021-04-12 18:01
could also potentially be android version, as android 25 is rather old and we've had to implement some work arounds for specifically old version in the past

**Comment by Nakonana** [comment] 2021-04-14 02:45
Still crashing on the other account, unfortunately. There was also an update available, so no the app version is 3.2.3 (2922), but the issue persists.

**Comment by shanaqui** [comment] 2021-04-14 12:49
Another report:

> Device: motorola XT1526
> Android Version: 22
> AppVersion: Version 3.2.3 (2922)
> BETA
> User ID: 75a3de27-866a-4dbd-a71b-ea80c8e93ef6
> Level: 91
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 240
> Details: When I click on the Guilds button, the app crashes immediately. Thanks in advance for any suggestions.

**Comment by phillipthelen** [comment] 2021-04-16 14:56
Fixed with the release version of 3.2.3

**Closed** 2021-04-16 14:56 UTC
Labels: Priority: minor, Status: issue: needs investigation, Type: Crash
