### ISSUE TITLE
Chat bar partially behind Navigation Buttons

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1181] opened 2019-06-07 22:01 UTC
In the last beta update of the application, the chat bar was somewhat hidden, making it impossible to chat properly

**Comment by matheusvictor** [comment] 2019-06-08 12:47
See this [screenshot](https://snag.gy/dvZm8l.jpg). For reasons of respect and privacy, I deleted the messages from users who were chatting in the Tavern at the time I made this screenshot.

**Comment by saraolson** [comment] 2019-06-10 16:41
we're doing our best to figure out what's causing this but it's proving tricky to understand. it seems linked to devices that arent running pure android 9, and thus is relatively widespread. won't release the next build until we fix this.

**Comment by matheusvictor** [comment] 2019-06-10 18:51
@saraolson, thanks for your answer. But, I'm running the Pure Android 9. So, maybe the problem is linked to size screen of devices. What do you think?

**Comment by phillipthelen** [comment] 2019-06-10 19:55
Interestingly we are unable to reproduce it on pixel or nexus devices running the same android version. However I ordered a xiaomi a2 lite to be able to reproduce this issue so that we can fix it, since it does look like it would affect a substantial number of users if fully released. I’m also closing this in favor of #1172, since they both are the same issue (the view that is pinned to the bottom of the screen is off screen)

--  
Phillip Thelen
Sent with Airmail

**Closed** 2019-06-10 19:56 UTC
Labels: Priority: important, Type: Bug
