### ISSUE TITLE
Dailies tab ignoring setting to show due tasks by default on launch

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1437] opened 2020-12-09 15:59 UTC
MaybeSteveRogers has reported a problem where dailies are showing both due and not due at once. Still not sure if this is the same issue as the one with completed/uncompleted to-dos, so let me know if it needs breaking out into an issue of its own!

> Device: OnePlus OnePlus 6T
> Android Version: 29
> AppVersion: バージョン： 3.1 (2675)
> User ID: 767e5d92-0e13-4e30-acb1-d8bba62824fc
> Level: 88
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7
> Timezone Offset: -60
> Details:
> 
> Dear Habitica team,
> 
> Overnight, my app has begun acting weirdly. When I opened it this morning (before CDS), it very briefly displayed no tasks at all before loading them as usual. This has never happened befhttps://assets.grammarly.com/emoji/v1/1f3af.svgore.
> 
> I have enabled the setting to "show only due" for Dailies. However, it now consistently shows "all". The setting is still enabled in Settings. Reloading content does not fix this; neither does closing and reopening the app. It keeps reverting to "all". 
> 
> As I said, this has literally happened overnight, I've not used the app in any way differently from what I normally do.

It seems likely this was caused by updating to 3.1, in this case, because they had just done that when the issue started.

May be related to #1407

**Comment by shanaqui** [comment] 2020-12-10 16:02
> Device: samsung Galaxy S10e
> Android Version: 29
> AppVersion: Version 3.1 (2675)
> User ID: 72fec49e-ae60-4d45-8996-b31b7ac168d0
> Level: 33
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 4
> Timezone Offset: 300

**Comment by Inquis1t0r** [comment] 2020-12-10 22:45
I would like to take this issue if possible.

**Comment by saraolson** [comment] 2020-12-11 15:15
@Inquis1t0r go ahead, i'll mark the issue as in progress for you

**Comment by shanaqui** [comment] 2021-02-01 13:06
@Inquis1t0r Hi! Just checking in how you're doing with this and whether you still want to work on it. If not, or if we don't hear back from you within a week, I'll put it back in the help wanted pool in case anyone else wants to give it a try!

**Comment by Inquis1t0r** [comment] 2021-02-04 08:08
@shanaqui Diving into your codebase took me some time, but im still working on it.

**Comment by cvuorinen** [comment] 2021-03-11 17:17
Should the current version of the app already have this fix? I have v 3.2.1 (2869) installed and it's still not working.

**Comment by saraolson** [comment] 2021-03-11 19:53
@cvuorinen it should, so if its still not working then that's a problem :/ thanks for letting us know its still effecting you. i'll reopen and mention it to phillip

**Comment by cvuorinen** [comment] 2021-03-11 20:26
@saraolson I did some more testing and seems like it's not working when I first open the app (and switch to Dailies tab), but if I first open some other view from the menu (e.g. Stats, Skills, Guilds or anything) and then come back to Tasks, then it's working.

**Comment by saraolson** [comment] 2021-03-12 14:58
@cvuorinen thanks for sharing that! hopefully that will help figure out whats wrong. in 3.2.1 we added a launch screen setting, so you can change the first screen the app launches to to your dailies. i was wondering if you've tried that and if the problem still happens then?

**Comment by cvuorinen** [comment] 2021-03-12 15:22
I tried it and the problem is still the same. First it's not working, but if I go to another view and come back, then it works.

**Comment by phillipthelen** [comment] 2021-03-12 16:43
@cvuorinen do you mean by that, that you go to another view and then use the back button to navigate back or that you tap the "tasks" menu item again?

**Comment by cvuorinen** [comment] 2021-03-12 17:10
@phillipthelen both ways works the same way.

**Comment by shanaqui** [comment] 2021-08-06 11:36
This is still occurring for the moderator MaybeSteveRogers:

"Despite clearing my cache and logging in and out multiple times, I still see all my Dailies when I open the app when I've set it to only display those that are due. I can temporarily "fix" it by going to a different page in the app entirely, and then sometimes when I return to my Tasks, only due Dailies are displayed; however I have to do this song and dance every single time I open the app.

Furthermore, I've set Dailies to be my default tab, but although the Dailies icon is highlighted at the bottom of my screen, it's my Habits that are displayed instead. This is also "fixed" by tapping to Habits, and then back to Dailies."

Device: OnePlus OnePlus 6T
Android Version: 29
AppVersion: バージョン： 3.3 (3008)
User ID: 767e5d92-0e13-4e30-acb1-d8bba62824fc
Level: 113
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 7
Timezone Offset: -120

**Comment by cvuorinen** [comment] 2021-08-06 14:39
Yep, same thing for me too.

**Comment by saraolson** [comment] 2021-08-09 12:58
this might be fixed in 3.3.1, i know we had a fix for the tab issue in there but not sure if that also helps the due by default. @cvuorinen are both the described issues happening on 3.3.1 for you?

**Comment by cvuorinen** [comment] 2021-08-09 18:27
@saraolson I'm not sure what you mean by "both", but it's still happening same way for me in 3.3.1

**Comment by saraolson** [comment] 2021-08-10 12:33
@cvuorinen by both i meant in the most recent report, the person brought up that the default setting isnt working and the bottom tab is highlighting the wrong screen

**Comment by cvuorinen** [comment] 2021-08-10 13:56
@saraolson I've never had the issue with the bottom bar highlighting wrong tab.

**Comment by saraolson** [comment] 2021-08-10 14:01
@cvuorinen alrighty, ty! will investigate the default dailies issue in 3.3.1 only then

**Comment by saraolson** [comment] 2022-02-23 18:35
Was just able to reproduce this issue still happening in 3.5.1.2

to reproduce:
-made a daily not due today
-make sure 'only show due' setting is checked
-force close app
-reopen app

the not-due daily shows. if i minimize the app and launch again, it is correctly filtered out then.

**Closed** 2022-03-29 13:43 UTC
Labels: Type: Bug, Help wanted, Priority: minor, Status: pr: ready for review
