### ISSUE TITLE
avatar on menu not displaying

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1893] opened 2023-01-03 18:19 UTC
> Device: Sony Xperia 1 III
> Android Version: 33
> AppVersion: Version 4.0.5 (4760)
> User ID: fa0a56f4-2bd0-4b2c-b232-6482d0ac8fe3
> Level: 93
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -60
> Details: 
> 
> Today I tried to fix it by doing the recommended options of clearing cache, etc, and even reinstalled the app completely. 
>
> ![Screenshot_20221229-002852](https://user-images.githubusercontent.com/102926641/210417409-269e3332-aa7f-4816-84d6-71297b998754.png)
>

**Comment by saraolson** [comment] 2023-01-04 14:54
ive also had this happen. on my old phone it eventually showed again while testing. then i got a new phone on the latest update and my avatar was gone again. it doesnt seem related to my account as all my test accounts dont show the avatar either

**Comment by phillipthelen** [comment] 2023-01-05 10:47
Duplicate of #1872

**Closed by phillipthelen** 2023-01-05 10:47 UTC
Labels: Type: Bug, Help wanted, Status: issue: needs investigation, Priority: minor
