### ISSUE TITLE
Submit feedback button not working for some

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1434] opened 2020-12-07 17:47 UTC
Non-responsive button reported by a user:

Device: LGE LM-G710
Android Version: 29
AppVersion: Version 3.1 (2675)
User ID: 66f6c6ce-ef54-403d-ad97-9144cbcd438c
Level: 32
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 3
Timezone Offset: 360

It works on build number 3677 on a Google Pixel 3, though, so I can't reproduce this.

**Comment by Nakonana** [comment] 2020-12-07 21:41
It's not working for me either (you'll probably see my email soon-ish - I sent it yesterday, I think)

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1 (2676)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 82
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60

**Comment by saraolson** [comment] 2020-12-11 15:06
"A few users have reported this -- I can't reproduce it in the beta version I have, though.

Device: Xiaomi Mi A1
Android Version: 28
AppVersion: Version 3.1 (2675)
User ID: c19f3a91-c81d-43ac-9341-0d707efe0802
Level: 60
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: -330"

included report from repeat issue

**Comment by Nakonana** [comment] 2020-12-11 23:27
@saraolson not that I'm aware of. Usually all links I see in the app open just fine. I also tried inserting the feedback form link in my tasks to see whether it wouldn't open but it did open using my standard browser. Also tried enabling the Chrome mobile browser, but the feedback button still doesn't do anything. It's not even trying to open a browser. It's like text that only looks like a button but isn't one.

**Comment by Nakonana** [comment] 2020-12-16 23:58
AppVersion: Version 3.1.1 (2687)
BETA

Still not working. (I skipped 2677?)

**Comment by Nakonana** [comment] 2020-12-18 10:31
Got to correct myself, it's working now on 2687. Not sure what happened in the meantime 🙃

**Comment by saraolson** [comment] 2021-01-04 19:27
@Nakonana glad to hear its working! Sometimes funky stuff just finds a way to right itself. Will close this issue unless people still encounter this in 2687 and above

**Closed by saraolson** 2021-01-04 19:27 UTC
Labels: Help wanted, Priority: minor, Type: Bug
