### ISSUE TITLE
App crashing for user on task load

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1514] opened 2021-03-22 09:26 UTC
> Hi! Next to last update made my app crush down inmediately when I try to run it...I installed last update (version 3.2.2) to see if it solved the problem, but there was no change. 
> I´m using android 10 (with last update) in a Huawei p40 lite E (if this information helps). 
> Any advice? 
> Thanks in advance! :)

I asked them to try clearing their cache, and it allowed them to open the app... but it crashed when loading tasks:

>  I´ve just tried to clear cache and data... it´s a bit weird, but when I cleared data, run the app and I could log-in without any problem...and then, just when it loaded my task list crushed down again 🙁

**Comment by saraolson** [comment] 2021-03-22 17:32
@shanaqui this sounds like something is wrong with this individual user's tasks? would prolly be helpful to look and see if they have any specific markdown, images, settings, or something that may be crashing it?

**Comment by Radd-max** [comment] 2021-03-23 12:59
Same issue. app crashed ass soon as I open it.did not have this issue in pervious versions.                                                     version: 3.2.2   device: nexus 6p   os: stock 8.1

**Comment by saraolson** [comment] 2021-03-23 14:58
@Radd-max do you use any markdown or special configurations on your tasks other than default settings? like perhaps monthly dailies, or really far out due dates. anything that may be notably outside the 'norm' of basic task creation and scheduling

**Comment by Radd-max** [comment] 2021-03-23 16:43
> @Radd-max do you use any markdown or special configurations on your tasks other than default settings? like perhaps monthly dailies, or really far out due dates. anything that may be notably outside the 'norm' of basic task creation and scheduling

Nope, not to my knowledge. The issue is gone now that I downgraded to v3.1.2. I guess ill just skip this update .

**Comment by shanaqui** [comment] 2021-03-24 00:01
@saraolson I've asked the user in question, but I can't look at their tasks if you meant for me to do that -- I don't have the accesses required.

**Comment by shanaqui** [comment] 2021-03-24 10:56
The user replied: "I don´t use markdowns (I don´t even know what it is, lol XD), emojis or images. About my task list, I have 72 to do tasks (not more than usual) and the oldest one is about december 2016.
In summary, nothing out of the ordinary (at least for me)."

**Comment by saraolson** [comment] 2021-03-24 15:04
@Radd-max thanks for following up, hopefully knowing it goes away in 3.1.2 will help us figure out what's going wrong.

@shanaqui gotcha, thanks for asking. so nothing too obvious. will look at this in the next milestone anyway.

**Comment by phillipthelen** [comment] 2021-03-25 11:13
This is fixed in the update that is rolling out today

**Closed** 2021-03-25 11:13 UTC
Labels: Type: Crash
