### ISSUE TITLE
Tapping back arrow in support categories opens menu instead of support hub (also pet categories)

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1841] opened 2022-08-22 20:36 UTC
To reproduce go to Menu > Support then 'Get Help' (or any of the purple buttons). Tap the back arrow in the top corner, and then menu will show instead of the support hub. 

The hardware back button does work, though.

**Comment by rilygreat** [comment] 2022-09-16 18:44
this also happens when accessing pets and mounts.

**Comment by AdamWier** [comment] 2022-09-29 15:37
Hello. I have reproduced this bug on my phone and would be interested in correcting it as part of Hacktoberfest.

**Comment by saraolson** [comment] 2022-10-03 16:18
@AdamWier great! i'll add the in progress label for you :)

**Comment by AdamWier** [comment] 2022-10-03 16:35
Great! Thanks! :) I'll get to it then

**Comment by AdamWier** [comment] 2022-10-07 21:11
As it turns out, this bug is no longer present on the development branch but still present in the current version distributed through the Play Store (at least for my phone). Is there a different branch that I should correct this on instead or should we just close the issue?

**Comment by saraolson** [comment] 2022-10-12 13:58
@AdamWier thanks for pointing that out! I also can't reproduce it on the beta build. i'll close this unless we're able to reproduce it again.

**Comment by saraolson** [comment] 2022-10-14 16:01
reopening this because i was just able to reproduce it. if you go to menu > challenges > tap into a challenge > then tap the top back button, it will make the behavior happen in other sections of the app.

for example i went to challenges, viewed a challenge, tapped back and the main menu came up. i then went to pets & mounts > dragons > tapped the top back button and the menu showed instead of taking me back to the pet hub.

**Closed** 2022-12-21 16:26 UTC
Labels: Type: Bug, Help wanted, Priority: minor
