### ISSUE TITLE
Quest invitation in wrong language

### ISSUE THREAD

**Issue by goldfndr** [HabitRPG/habitica-android#634] opened 2016-09-30 10:39 UTC
I was recently invited to a quest, and although the e-mail was correctly in my native language, English, "**______ needs your help to defeat the terrifying Boss of "Recidivate, Part 2: Recidivate the Necromancer" on Habitica!**", the notification on my Android device was in French:
* **Invitation à une Quête** (title)
* **Invitation à la Quête Récidive, Partie 2 : Récidive la Nécromancienne** (text)

I'm guessing that this happened because the account holder of the quest owner uses French as her native language.

This occurred with Habitica version 0.0.33.2; now that I've updated to 0.0.34, I see that it didn't have my language (English) selected, but I don't know if that makes a difference.

**Comment by vIiRuS** [comment] 2016-10-13 12:19
This is a duplicate of #604

**Closed** 2016-10-14 10:53 UTC
