### ISSUE TITLE
Widget is not synced with web unless the app is opened

### ISSUE THREAD

**Issue by balaji303** [HabitRPG/habitica-android#1450] opened 2020-12-27 10:37 UTC
**Describe the bug**
Widget is not synced with web unless the app is opened
**To Reproduce**
1. I closed taskA on web
2. Open mobile screen and can also see the same taskA unclosed in mobile widget
3. Open and close habitica app without any changes
4. Now if I see the widget, the taskA is closed

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G3
 - OS: Android 6
 - App Version: 3.0.2
 - Habitica Username: @balajiv

**Additional context**

**Comment by shanaqui** [comment] 2021-01-14 14:05
This looks like a duplicate of #1233 -- should we close one of the two?

**Closed** 2021-01-14 16:55 UTC
Labels: Help wanted, Priority: minor, Type: Bug
